import { file, n, resolveAnsi } from './shared.js';

const face = (name, attributes) => `'(${name} ((t (${attributes}))))`;
const foregroundFace = (name, color) => face(name, `:foreground "${color}"`);
const backgroundFace = (name, color) => face(name, `:background "${color}"`);

export function emitEmacsTheme(theme, ansiMapping) {
  const colors = Object.fromEntries(Object.entries(theme.colors).map(([name, hex]) => [name, n(hex)]));
  const ansi = resolveAnsi(ansiMapping, theme.colors).map((hex) => `"${hex}"`).join(' ');
  const name = `candela-${theme.id}`;
  const lines = [
    `;;; ${name}-theme.el --- Candela ${theme.name} -*- lexical-binding: t; -*-`,
    ';; Generated by scripts/generate.js, do not edit.',
    '',
    `(deftheme ${name} "Candela ${theme.name}.")`,
    '',
    '(custom-theme-set-faces',
    ` '${name}`,
    ` ${face('default', `:background "${colors.bg}" :foreground "${colors.ink}"`)}`,
    ` ${backgroundFace('cursor', colors.cursor)}`,
    ` ${backgroundFace('region', colors.selection)}`,
    ` ${backgroundFace('hl-line', colors.lineHighlight)}`,
    ` ${backgroundFace('fringe', colors.surface)}`,
    ` ${face('mode-line', `:background "${colors.surface}" :foreground "${colors.ink}"`)}`,
    ` ${face('header-line', `:background "${colors.surface}" :foreground "${colors.ink}"`)}`,
    ` ${foregroundFace('vertical-border', colors.border)}`,
    ` ${foregroundFace('window-divider', colors.border)}`,
    ` ${foregroundFace('line-number', colors.ink2)}`,
    ` ${foregroundFace('line-number-current-line', colors.ink)}`,
    ` ${foregroundFace('font-lock-comment-face', colors.faint)}`,
    ` ${foregroundFace('font-lock-doc-face', colors.faint)}`,
    ` ${foregroundFace('font-lock-keyword-face', colors.kw)}`,
    ` ${foregroundFace('font-lock-string-face', colors.str)}`,
    ` ${foregroundFace('font-lock-function-name-face', colors.fn)}`,
    ` ${foregroundFace('font-lock-constant-face', colors.num)}`,
    ` ${foregroundFace('font-lock-number-face', colors.num)}`,
    ` ${foregroundFace('font-lock-type-face', colors.type)}`,
    ` ${foregroundFace('font-lock-builtin-face', colors.builtin)}`,
    ` ${foregroundFace('font-lock-variable-name-face', colors.builtin)}`,
    ` ${foregroundFace('font-lock-punctuation-face', colors.punct)}`,
    ` ${foregroundFace('font-lock-operator-face', colors.punct)}`,
    ` ${foregroundFace('error', colors.error)}`,
    ` ${foregroundFace('diff-removed', colors.error)}`,
    ` ${foregroundFace('warning', colors.warning)}`,
    ` ${foregroundFace('success', colors.ok)}`,
    ` ${foregroundFace('diff-added', colors.ok)}`,
    ` ${foregroundFace('link', colors.fn)}`,
    ` ${foregroundFace('minibuffer-prompt', colors.builtin)}`,
    ` ${face('isearch', `:background "${colors.selection}" :foreground "${colors.ink}"`)}`,
    ` ${face('lazy-highlight', `:background "${colors.selection}" :foreground "${colors.ink}"`)})`,
    '',
    '(custom-theme-set-variables',
    ` '${name}`,
    ` '(ansi-color-names-vector [${ansi}])`,
    ` '(frame-background-mode '${theme.mode}))`,
    '',
    `(provide-theme '${name})`,
    '',
  ];
  return lines.join('\n');
}

export const emacsThemeFile = (theme, ansiMapping, prefix = '') =>
  file(`${prefix}candela-${theme.id}-theme.el`, emitEmacsTheme(theme, ansiMapping));

export const emitEmacsPackage = (theme, ansiMapping) => ({ files: [emacsThemeFile(theme, ansiMapping)] });
