// Helix emitter. One theme TOML per theme: top-level scope keys reference named
// palette entries, and a [palette] table at the bottom carries every Candela
// token as a hex value. Scope keys follow the README roles.

import { normalizeHex } from '../colors.js';
import { file } from './shared.js';

// Chrome scopes, which take inline tables rather than a bare palette name.
const HELIX_UI = [
  '"ui.background" = { bg = "bg" }',
  '"ui.text" = "ink"',
  '"ui.window" = { fg = "border" }',
  '"ui.linenr" = "ink2"',
  '"ui.linenr.selected" = "ink"',
  '"ui.cursor" = { fg = "bg", bg = "cursor" }',
  '"ui.cursor.primary" = { fg = "bg", bg = "cursor" }',
  '"ui.selection" = { bg = "selection" }',
  '"ui.cursorline" = { bg = "lineHighlight" }',
  '"ui.statusline" = { fg = "ink", bg = "surface" }',
  '"ui.popup" = { bg = "surface" }',
  '"ui.menu" = { fg = "ink", bg = "surface" }',
  '"ui.help" = { fg = "ink", bg = "surface" }',
  '"ui.virtual.whitespace" = "faint"',
  '"ui.virtual.ruler" = { bg = "border" }',
];

// Helix scope key -> Candela palette name, plain foreground scopes.
const HELIX_SYNTAX = [
  ['keyword', 'kw'],
  ['keyword.storage', 'kw'],
  ['string', 'str'],
  ['constant.character', 'str'],
  ['function', 'fn'],
  ['function.method', 'fn'],
  ['constant', 'num'],
  ['constant.numeric', 'num'],
  ['type', 'type'],
  ['type.builtin', 'type'],
  ['constructor', 'type'],
  ['variable.builtin', 'builtin'],
  ['variable.other.member', 'builtin'],
  ['label', 'builtin'],
  ['punctuation', 'punct'],
  ['operator', 'punct'],
  ['comment', 'faint'],
  // Helix scopes markup tags as `tag`; unmapped, HTML/JSX/XML tags render flat.
  ['tag', 'type'],
  ['attribute', 'builtin'],
  ['string.regexp', 'str'],
  ['constant.character.escape', 'num'],
  ['diff.plus', 'ok'],
  ['diff.minus', 'error'],
  ['diff.delta', 'warning'],
  // Markdown and other prose grammars (see TOKEN_SCOPES): unmapped means flat text.
  ['markup.heading', 'fn'],
  ['markup.bold', 'kw'],
  ['markup.italic', 'kw'],
  ['markup.raw', 'builtin'],
  ['markup.link.text', 'fn'],
  ['markup.link.url', 'fn'],
  ['markup.list', 'punct'],
  ['markup.quote', 'faint'],
];

// Bare diagnostic keys Helix reads outside the "scope" namespace.
const HELIX_DIAGNOSTICS = [
  '"diagnostic.error" = "error"',
  '"diagnostic.warning" = "warning"',
  'error = "error"',
  'warning = "warning"',
  'hint = "faint"',
  'info = "fn"',
];

export function emitHelixTheme(theme) {
  return [
    `# Candela ${theme.name} — generated by scripts/generate.js, do not edit.`,
    ...HELIX_UI,
    ...HELIX_SYNTAX.map(([scope, token]) => `"${scope}" = "${token}"`),
    ...HELIX_DIAGNOSTICS,
    '',
    '[palette]',
    ...Object.entries(theme.colors).map(([token, hex]) => `${token} = "${normalizeHex(hex)}"`),
    '',
  ].join('\n');
}

export const helixThemeFile = (theme, prefix = '') =>
  file(`${prefix}candela-${theme.id}.toml`, emitHelixTheme(theme));
