// Neovim emitter. One self-contained Lua colorscheme per theme. Chosen over a
// base16 YAML: a Lua colorscheme drops into runtimepath and loads with
// `:colorscheme candela-<id>` and zero plugins, where a base16 YAML needs the
// base16 builder/plugin to apply at all. It sets legacy highlight groups (Neovim
// links Treesitter groups to these by default) plus the 16 terminal_color_N
// globals from the shared ansiMapping.

import { n, resolveAnsi, file } from './shared.js';

// Legacy highlight group -> Candela token (foreground). Comments get italic.
const NVIM_SYNTAX = [
  ['Comment', 'faint', 'italic'],
  ['Constant', 'num'],
  ['String', 'str'],
  ['Character', 'str'],
  ['Number', 'num'],
  ['Boolean', 'num'],
  ['Identifier', 'ink'],
  ['Function', 'fn'],
  ['Statement', 'kw'],
  ['Keyword', 'kw'],
  ['Operator', 'punct'],
  ['PreProc', 'builtin'],
  ['Type', 'type'],
  ['Special', 'builtin'],
  ['Delimiter', 'punct'],
  ['Todo', 'kw'],
  ['Error', 'error'],
  ['WarningMsg', 'warning'],
  // Markdown and other prose grammars (see TOKEN_SCOPES). Neovim links @markup.* to
  // defaults this colorscheme never set, so headings rendered as plain text.
  ['Title', 'fn', 'bold'],
  ['@markup.heading', 'fn', 'bold'],
  ['@markup.strong', 'kw', 'bold'],
  ['@markup.italic', 'kw', 'italic'],
  ['@markup.raw', 'builtin'],
  ['@markup.link.label', 'fn'],
  ['@markup.link.url', 'fn', 'underline'],
  ['@markup.quote', 'faint', 'italic'],
  ['@markup.list', 'punct'],
  // Treesitter groups whose default link lands on Identifier (i.e. plain `ink`):
  // object/JSON keys and markup tags, the same gap as Zed's `property`/`tag`.
  ['@property', 'builtin'],
  ['@variable.member', 'builtin'],
  ['@tag', 'type'],
  ['@tag.attribute', 'builtin'],
  ['@string.escape', 'num'],
  ['@diff.plus', 'ok'],
  ['@diff.minus', 'error'],
  ['@diff.delta', 'warning'],
];

function luaHl(group, opts) {
  const parts = Object.entries(opts).map(([k, v]) =>
    typeof v === 'boolean' ? `${k} = ${v}` : `${k} = '${v}'`,
  );
  return `hi('${group}', { ${parts.join(', ')} })`;
}

export function emitNvimTheme(theme, ansiMapping) {
  const c = theme.colors;
  const lines = [
    `-- Candela ${theme.name} — generated by scripts/generate.js, do not edit.`,
    "vim.cmd('highlight clear')",
    "if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end",
    `vim.o.background = '${theme.mode}'`,
    `vim.g.colors_name = 'candela-${theme.id}'`,
    '',
    'local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end',
    '',
    luaHl('Normal', { fg: n(c.ink), bg: n(c.bg) }),
    luaHl('NormalFloat', { fg: n(c.ink), bg: n(c.surface) }),
    luaHl('LineNr', { fg: n(c.ink2) }),
    luaHl('CursorLine', { bg: n(c.lineHighlight) }),
    luaHl('CursorLineNr', { fg: n(c.ink) }),
    luaHl('Cursor', { fg: n(c.bg), bg: n(c.cursor) }),
    luaHl('Visual', { bg: n(c.selection) }),
    luaHl('VertSplit', { fg: n(c.border) }),
    luaHl('WinSeparator', { fg: n(c.border) }),
    luaHl('Pmenu', { fg: n(c.ink), bg: n(c.surface) }),
    luaHl('PmenuSel', { bg: n(c.selection) }),
    luaHl('StatusLine', { fg: n(c.ink), bg: n(c.surface) }),
    luaHl('DiffAdd', { fg: n(c.ok) }),
    luaHl('DiffDelete', { fg: n(c.error) }),
    luaHl('DiffChange', { fg: n(c.warning) }),
    // `highlight clear` restores Neovim's built-in defaults for anything a colorscheme
    // leaves unset — bright yellow search, saturated red diagnostics. Those are the
    // loudest colors on screen and none of them come from the palette, so every group
    // Neovim defaults to a hardcoded hue gets set here.
    luaHl('Search', { fg: n(c.ink), bg: n(c.selection) }),
    luaHl('IncSearch', { fg: n(c.bg), bg: n(c.warning) }),
    luaHl('CurSearch', { fg: n(c.bg), bg: n(c.warning) }),
    luaHl('MatchParen', { fg: n(c.ink), bg: n(c.selection) }),
    luaHl('Folded', { fg: n(c.ink2), bg: n(c.surface) }),
    luaHl('FoldColumn', { fg: n(c.faint) }),
    luaHl('SignColumn', { fg: n(c.ink2) }),
    luaHl('NonText', { fg: n(c.faint) }),
    luaHl('Whitespace', { fg: n(c.faint) }),
    luaHl('SpecialKey', { fg: n(c.faint) }),
    luaHl('ColorColumn', { bg: n(c.lineHighlight) }),
    luaHl('QuickFixLine', { bg: n(c.selection) }),
    luaHl('StatusLineNC', { fg: n(c.ink2), bg: n(c.surface) }),
    luaHl('TabLine', { fg: n(c.ink2), bg: n(c.bg) }),
    luaHl('TabLineSel', { fg: n(c.ink), bg: n(c.surface) }),
    luaHl('TabLineFill', { bg: n(c.bg) }),
    luaHl('WinBar', { fg: n(c.ink), bg: n(c.bg) }),
    luaHl('WinBarNC', { fg: n(c.ink2), bg: n(c.bg) }),
    luaHl('FloatBorder', { fg: n(c.border), bg: n(c.surface) }),
    luaHl('FloatTitle', { fg: n(c.ink), bg: n(c.surface) }),
    luaHl('Directory', { fg: n(c.fn) }),
    luaHl('Question', { fg: n(c.fn) }),
    luaHl('MoreMsg', { fg: n(c.ok) }),
    luaHl('ModeMsg', { fg: n(c.ink) }),
    luaHl('ErrorMsg', { fg: n(c.error) }),
    luaHl('Underlined', { fg: n(c.fn), underline: true }),
    luaHl('DiagnosticError', { fg: n(c.error) }),
    luaHl('DiagnosticWarn', { fg: n(c.warning) }),
    luaHl('DiagnosticInfo', { fg: n(c.fn) }),
    luaHl('DiagnosticHint', { fg: n(c.faint) }),
    luaHl('DiagnosticOk', { fg: n(c.ok) }),
    luaHl('DiagnosticUnderlineError', { sp: n(c.error), undercurl: true }),
    luaHl('DiagnosticUnderlineWarn', { sp: n(c.warning), undercurl: true }),
    luaHl('DiagnosticUnderlineInfo', { sp: n(c.fn), undercurl: true }),
    luaHl('DiagnosticUnderlineHint', { sp: n(c.faint), undercurl: true }),
  ];
  for (const [group, token, style] of NVIM_SYNTAX) {
    const opts = { fg: n(c[token]) };
    if (style) opts[style] = true;
    lines.push(luaHl(group, opts));
  }

  lines.push('');
  const ansi = resolveAnsi(ansiMapping, c);
  ansi.forEach((hex, i) => lines.push(`vim.g.terminal_color_${i} = '${hex}'`));
  lines.push('');
  return lines.join('\n');
}

export const nvimThemeFile = (theme, ansiMapping, prefix = '') =>
  file(`${prefix}candela-${theme.id}.lua`, emitNvimTheme(theme, ansiMapping));

export const emitNvimPackage = (theme, ansiMapping) => ({ files: [nvimThemeFile(theme, ansiMapping)] });
