// Neovim emitter. One self-contained Lua colorscheme per theme. Chosen over a
// base16 YAML: a Lua colorscheme drops into runtimepath and loads with
// `:colorscheme candela-<id>` and zero plugins, where a base16 YAML needs the
// base16 builder/plugin to apply at all. It sets legacy highlight groups (Neovim
// links Treesitter groups to these by default) plus the 16 terminal_color_N
// globals from the shared ansiMapping.

import { n, resolveAnsi, file } from './shared.js';
import { NVIM_SYNTAX, VIM_UI_HIGHLIGHTS } from './vim-groups.js';


function luaHl(group, opts) {
  const parts = Object.entries(opts).map(([k, v]) =>
    typeof v === 'boolean' ? `${k} = ${v}` : `${k} = '${v}'`,
  );
  return `hi('${group}', { ${parts.join(', ')} })`;
}

export function emitNvimTheme(theme, ansiMapping) {
  const c = theme.colors;
  const lines = [
    `-- Candela ${theme.name} — generated by scripts/generate.js, do not edit.`,
    "vim.cmd('highlight clear')",
    "if vim.fn.exists('syntax_on') == 1 then vim.cmd('syntax reset') end",
    `vim.o.background = '${theme.mode}'`,
    `vim.g.colors_name = 'candela-${theme.id}'`,
    '',
    'local hi = function(group, opts) vim.api.nvim_set_hl(0, group, opts) end',
    '',
  ];
  for (const [group, attributes] of VIM_UI_HIGHLIGHTS) {
    const opts = Object.fromEntries(Object.entries(attributes).map(([attribute, tokenOrStyle]) => [
      attribute,
      typeof tokenOrStyle === 'string' ? n(c[tokenOrStyle]) : tokenOrStyle,
    ]));
    lines.push(luaHl(group, opts));
  }
  for (const [group, token, style] of NVIM_SYNTAX) {
    const opts = { fg: n(c[token]) };
    if (style) opts[style] = true;
    lines.push(luaHl(group, opts));
  }

  lines.push('');
  const ansi = resolveAnsi(ansiMapping, c);
  ansi.forEach((hex, i) => lines.push(`vim.g.terminal_color_${i} = '${hex}'`));
  lines.push('');
  return lines.join('\n');
}

export const nvimThemeFile = (theme, ansiMapping, prefix = '') =>
  file(`${prefix}candela-${theme.id}.lua`, emitNvimTheme(theme, ansiMapping));

export const emitNvimPackage = (theme, ansiMapping) => ({ files: [nvimThemeFile(theme, ansiMapping)] });
