import { hexToRgb } from '../colors.js';
import { file, HOMEPAGE_URL, n, DEFAULT_VERSION } from './shared.js';

const MIN_APP_VERSION = '1.0.0';

const COLOR_VARIABLES = [
  ['--background-primary', 'bg'],
  ['--background-primary-alt', 'surface'],
  ['--background-secondary', 'surface'],
  ['--background-secondary-alt', 'surface'],
  ['--modal-background', 'surface'],
  ['--background-modifier-hover', 'lineHighlight'],
  ['--background-modifier-active-hover', 'selection'],
  ['--background-modifier-border', 'border'],
  ['--background-modifier-border-hover', 'ink2'],
  ['--background-modifier-border-focus', 'builtin'],
  ['--interactive-normal', 'surface'],
  ['--interactive-hover', 'lineHighlight'],
  ['--interactive-accent', 'builtin'],
  ['--interactive-accent-hover', 'builtin'],
  ['--text-normal', 'ink'],
  ['--text-muted', 'ink2'],
  ['--text-faint', 'faint'],
  ['--text-accent', 'builtin'],
  ['--color-accent', 'builtin'],
  ['--text-selection', 'selection'],
  ['--caret-color', 'cursor'],
  ['--text-error', 'error'],
  ['--text-success', 'ok'],
  ['--code-background', 'surface'],
  ['--code-normal', 'ink'],
  ['--code-comment', 'faint'],
  ['--code-keyword', 'kw'],
  ['--code-string', 'str'],
  ['--code-function', 'fn'],
  ['--code-value', 'num'],
  ['--code-important', 'num'],
  ['--code-tag', 'type'],
  ['--code-property', 'type'],
  ['--code-punctuation', 'punct'],
  ['--code-operator', 'punct'],
  ['--color-red', 'error'],
  ['--color-orange', 'warning'],
  ['--color-yellow', 'num'],
  ['--color-green', 'ok'],
  ['--color-blue', 'builtin'],
  ['--color-purple', 'type'],
];

const className = (theme) => `candela-${theme.id}`;

function mixHex(start, end, endWeight) {
  const startRgb = hexToRgb(start);
  const endRgb = hexToRgb(end);
  const channel = (name) => Math.round(startRgb[name] * (1 - endWeight) + endRgb[name] * endWeight).toString(16).padStart(2, '0');
  return `#${channel('r')}${channel('g')}${channel('b')}`;
}

function baseColorVariables(theme) {
  const c = theme.colors;
  const colors = theme.mode === 'light'
    ? [c.surface, mixHex(c.surface, c.bg, 0.3), c.bg, c.lineHighlight, mixHex(c.lineHighlight, c.border, 0.45), c.border, mixHex(c.border, c.ink2, 0.2), mixHex(c.border, c.ink2, 0.45), c.ink2, mixHex(c.ink2, c.ink, 0.35), mixHex(c.ink2, c.ink, 0.65), c.ink]
    : [c.bg, mixHex(c.bg, c.surface, 0.35), c.surface, c.lineHighlight, mixHex(c.lineHighlight, c.border, 0.25), mixHex(c.lineHighlight, c.border, 0.5), mixHex(c.lineHighlight, c.border, 0.75), c.border, mixHex(c.border, c.ink2, 0.35), mixHex(c.border, c.ink2, 0.7), c.ink2, c.ink];
  return ['00', '05', '10', '20', '25', '30', '35', '40', '50', '60', '70', '100']
    .map((level, index) => [`--color-base-${level}`, colors[index]]);
}

function cssVariables(theme) {
  return [...COLOR_VARIABLES.map(([variable, token]) => [variable, theme.colors[token]]), ...baseColorVariables(theme)]
    .map(([variable, color]) => `  ${variable}: ${n(color)};`)
    .join('\n');
}

function paletteBlock(theme, selector) {
  return `${selector} {\n${cssVariables(theme)}\n}`;
}

function paletteSettings(themes, mode) {
  const modeThemes = themes.filter((theme) => theme.mode === mode);
  const defaultTheme = modeThemes[0];
  return [
    '  -',
    `    id: ${mode}-palette`,
    `    title: ${mode[0].toUpperCase() + mode.slice(1)} palette`,
    '    type: class-select',
    '    allowEmpty: false',
    `    default: ${className(defaultTheme)}`,
    '    options:',
    ...modeThemes.flatMap((theme) => [
      '      -',
      `        label: ${JSON.stringify(theme.name)}`,
      `        value: ${className(theme)}`,
    ]),
  ];
}

function settingsBlock(themes) {
  return [
    '/* @settings',
    '',
    'name: Candela',
    'id: candela',
    'settings:',
    ...paletteSettings(themes, 'light'),
    ...paletteSettings(themes, 'dark'),
    '*/',
  ].join('\n');
}

export function obsidianThemeCss(themes, includeSettings = true) {
  const defaults = ['light', 'dark']
    .map((mode) => themes.find((theme) => theme.mode === mode))
    .filter(Boolean)
    .map((theme) => paletteBlock(theme, `.theme-${theme.mode}`));
  const palettes = themes.map((theme) => paletteBlock(theme, `body.theme-${theme.mode}.${className(theme)}`));
  return [...(includeSettings ? [settingsBlock(themes)] : []), ...defaults, ...palettes, ''].join('\n\n');
}

export function obsidianManifest(version = DEFAULT_VERSION) {
  return {
    name: 'Candela',
    version,
    minAppVersion: MIN_APP_VERSION,
    author: 'Candela',
    authorUrl: HOMEPAGE_URL,
  };
}

export const obsidianReadme = `# Candela for Obsidian

1. Copy the \`Candela\` folder into your vault's \`.obsidian/themes/\` directory.
2. Open **Settings → Appearance** and select **Candela**.
3. Optionally install Style Settings to choose light and dark palettes separately.

Generated by Candela Themes.
`;

export function emitObsidianTheme(theme) {
  return {
    files: [
      file('Candela/manifest.json', JSON.stringify(obsidianManifest(), null, 2) + '\n'),
      file('Candela/theme.css', obsidianThemeCss([theme], false)),
    ],
  };
}
