// Sublime Text emitter. One .sublime-color-scheme (JSON) per theme: variables
// hold the palette, globals wire the editor chrome, rules[] map the same
// TextMate scopes as VS Code (reusing TOKEN_SCOPES) to those variables.

import { normalizeHex, hexToHsl } from '../colors.js';
import { file } from './shared.js';
import { TOKEN_SCOPES } from './scopes.js';

// Ships inside the Sublime package. Only Adaptive.sublime-theme reads a color
// scheme's `--background`/`--accent` variables, so a Candela scheme on any other
// theme recolors the editor but leaves the chrome stock gray. Sublime has no
// declarative way for a color scheme to request a UI theme, hence the plugin.
// It asks once and remembers the answer — silently rewriting someone's `theme`
// setting is the kind of surprise that earns bug reports.
export const SUBLIME_ADAPTIVE_PLUGIN = `# Candela — generated by scripts/generate.js, do not edit.
# Offers to switch the UI theme to Adaptive when a Candela color scheme is active,
# so the sidebar, tabs and status bar follow the palette instead of staying gray.

import sublime
import sublime_plugin

ADAPTIVE = "Adaptive.sublime-theme"
PREFERENCES = "Preferences.sublime-settings"
STATE = "Candela.sublime-settings"


def _uses_candela(preferences):
    return "candela-" in preferences.get("color_scheme", "")


def _theme_follows_color_scheme(preferences):
    # "auto" resolves to light_theme/dark_theme, so check those instead.
    theme = preferences.get("theme", "auto")
    if theme != "auto":
        return theme == ADAPTIVE
    light = preferences.get("light_theme", "Default.sublime-theme")
    dark = preferences.get("dark_theme", "Default Dark.sublime-theme")
    return light == ADAPTIVE and dark == ADAPTIVE


def _use_adaptive():
    preferences = sublime.load_settings(PREFERENCES)
    preferences.set("theme", ADAPTIVE)
    sublime.save_settings(PREFERENCES)


def _offer_adaptive():
    preferences = sublime.load_settings(PREFERENCES)
    if not _uses_candela(preferences) or _theme_follows_color_scheme(preferences):
        return
    state = sublime.load_settings(STATE)
    if state.get("adaptive_prompt_answered", False):
        return
    # Recorded before the dialog so a crash or a force-quit mid-prompt cannot turn
    # the ask into a loop on every startup.
    state.set("adaptive_prompt_answered", True)
    sublime.save_settings(STATE)
    if sublime.ok_cancel_dialog(
        "Candela can also color the sidebar, tabs and status bar.\\n\\n"
        "That needs the Adaptive UI theme. Switch to it?",
        "Use Adaptive",
    ):
        _use_adaptive()


class CandelaUseAdaptiveUiCommand(sublime_plugin.ApplicationCommand):
    """Palette entry, so declining the prompt once is not permanent."""

    def run(self):
        _use_adaptive()

    def is_enabled(self):
        return not _theme_follows_color_scheme(sublime.load_settings(PREFERENCES))


def plugin_loaded():
    preferences = sublime.load_settings(PREFERENCES)
    preferences.add_on_change("candela_adaptive_ui", lambda: sublime.set_timeout(_offer_adaptive, 0))
    sublime.set_timeout(_offer_adaptive, 500)


def plugin_unloaded():
    sublime.load_settings(PREFERENCES).clear_on_change("candela_adaptive_ui")
`;

// Syntax token whose hue sits closest to `targetHue` on the color wheel.
function nearestHueToken(colors, targetHue) {
  const candidates = ['kw', 'str', 'fn', 'num', 'type', 'builtin'];
  let best = candidates[0];
  let bestDistance = Infinity;
  for (const token of candidates) {
    const { h } = hexToHsl(colors[token]);
    const distance = Math.min(Math.abs(h - targetHue), 360 - Math.abs(h - targetHue));
    if (distance < bestDistance) {
      bestDistance = distance;
      best = token;
    }
  }
  return best;
}

export function emitSublimeScheme(theme) {
  const c = theme.colors;
  const variables = {};
  for (const [token, hex] of Object.entries(c)) {
    variables[token] = normalizeHex(hex);
  }
  // Sublime exposes `--`-prefixed scheme variables to the UI theme, which is the only
  // way a color scheme can tint the chrome (sidebar, tabs, status bar). Adaptive
  // blends every chrome surface off --background and colors the sidebar git badges
  // from the hue family below. Our diagnostics are hue-locked by the invariants
  // (error vermillion, warning amber, ok blue-green), so they map straight across;
  // --bluish has no fixed token, so pick the syntax color closest to blue.
  variables['--background'] = 'var(bg)';
  variables['--foreground'] = 'var(ink)';
  variables['--accent'] = 'var(builtin)';
  variables['--redish'] = 'var(error)';
  variables['--orangish'] = 'var(warning)';
  variables['--greenish'] = 'var(ok)';
  variables['--bluish'] = `var(${nearestHueToken(c, 210)})`;
  const doc = {
    name: `Candela ${theme.name}`,
    author: 'Candela',
    variables,
    globals: {
      background: 'var(surface)',
      foreground: 'var(ink)',
      caret: 'var(cursor)',
      line_highlight: 'var(lineHighlight)',
      selection: 'var(selection)',
      gutter: 'var(bg)',
      gutter_foreground: 'var(ink2)',
      invisibles: 'var(faint)',
      accent: 'var(builtin)',
    },
    rules: TOKEN_SCOPES.map(({ token, scopes, fontStyle }) => {
      const rule = { scope: scopes.join(', '), foreground: `var(${token})` };
      if (fontStyle) rule.font_style = fontStyle;
      return rule;
    }),
  };
  return JSON.stringify(doc, null, 2) + '\n';
}

export const sublimeSchemeFile = (theme, prefix = '') =>
  file(`${prefix}candela-${theme.id}.sublime-color-scheme`, emitSublimeScheme(theme));
