import assert from 'node:assert/strict';
import test from 'node:test';
import source from '../../themes/candela-themes.json' with { type: 'json' };
import { emitFullFamily, FORMAT_EMITTERS, installReadme } from './index.js';
import { ANSI_ORDER, resolveAnsi } from './shared.js';

const WARP_ANSI_ORDER = ['black', 'blue', 'cyan', 'green', 'magenta', 'red', 'white', 'yellow'];

test('Warp themes use the expected YAML fields and named ANSI colors', () => {
  const { themes, ansiMapping } = source;
  const warp = FORMAT_EMITTERS.find((format) => format.tool === 'warp');
  assert.equal(warp.label, 'Warp');
  assert.match(installReadme('warp', themes[0]), /\.warp\/themes/);

  for (const theme of [themes.find((candidate) => candidate.mode === 'light'), themes.find((candidate) => candidate.mode === 'dark')]) {
    const output = warp.emit(theme, ansiMapping).files[0];
    const ansi = resolveAnsi(ansiMapping, theme.colors);
    const normal = Object.fromEntries(ANSI_ORDER.map((name, index) => [name, ansi[index]]));
    const bright = Object.fromEntries(ANSI_ORDER.map((name, index) => [name, ansi[index + 8]]));

    assert.equal(output.path, `candela-${theme.id}.yaml`);
    assert.match(output.content, new RegExp(`# Candela ${theme.name} — generated by scripts/generate\\.js, do not edit\\.`));
    assert.match(output.content, new RegExp(`name: Candela ${theme.name}`));
    assert.match(output.content, new RegExp(`accent: '${theme.colors.builtin}'`));
    assert.match(output.content, new RegExp(`background: '${theme.colors.bg}'`));
    assert.match(output.content, new RegExp(`foreground: '${theme.colors.ink}'`));
    assert.match(output.content, new RegExp(`cursor: '${theme.colors.cursor}'`));
    assert.match(output.content, new RegExp(`details: ${theme.mode === 'dark' ? 'darker' : 'lighter'}`));
    for (const [group, colors] of [['normal', normal], ['bright', bright]]) {
      const section = [`  ${group}:`, ...WARP_ANSI_ORDER.map((name) => `    ${name}: '${colors[name]}'`)].join('\\n');
      assert.match(output.content, new RegExp(section));
    }
  }

  const files = emitFullFamily(themes, ansiMapping, '', '').files
    .filter((entry) => entry.path.startsWith('warp/'));
  assert.deepEqual(files.map((entry) => entry.path), themes.map((theme) => `warp/candela-${theme.id}.yaml`));
});
