// Highlight groups shared by Vim and Neovim. Both editors use the same legacy
// group names; only their configuration syntax differs.

export const VIM_UI_HIGHLIGHTS = [
  ['Normal', { fg: 'ink', bg: 'bg' }],
  ['NormalFloat', { fg: 'ink', bg: 'surface' }],
  ['LineNr', { fg: 'ink2' }],
  ['CursorLine', { bg: 'lineHighlight' }],
  ['CursorLineNr', { fg: 'ink' }],
  ['Cursor', { fg: 'bg', bg: 'cursor' }],
  ['Visual', { bg: 'selection' }],
  ['VertSplit', { fg: 'border' }],
  ['WinSeparator', { fg: 'border' }],
  ['Pmenu', { fg: 'ink', bg: 'surface' }],
  ['PmenuSel', { bg: 'selection' }],
  ['StatusLine', { fg: 'ink', bg: 'surface' }],
  ['DiffAdd', { fg: 'ok' }],
  ['DiffDelete', { fg: 'error' }],
  ['DiffChange', { fg: 'warning' }],
  ['Search', { fg: 'ink', bg: 'selection' }],
  ['IncSearch', { fg: 'bg', bg: 'warning' }],
  ['CurSearch', { fg: 'bg', bg: 'warning' }],
  ['MatchParen', { fg: 'ink', bg: 'selection' }],
  ['Folded', { fg: 'ink2', bg: 'surface' }],
  ['FoldColumn', { fg: 'faint' }],
  ['SignColumn', { fg: 'ink2' }],
  ['NonText', { fg: 'faint' }],
  ['Whitespace', { fg: 'faint' }],
  ['SpecialKey', { fg: 'faint' }],
  ['ColorColumn', { bg: 'lineHighlight' }],
  ['QuickFixLine', { bg: 'selection' }],
  ['StatusLineNC', { fg: 'ink2', bg: 'surface' }],
  ['TabLine', { fg: 'ink2', bg: 'bg' }],
  ['TabLineSel', { fg: 'ink', bg: 'surface' }],
  ['TabLineFill', { bg: 'bg' }],
  ['WinBar', { fg: 'ink', bg: 'bg' }],
  ['WinBarNC', { fg: 'ink2', bg: 'bg' }],
  ['FloatBorder', { fg: 'border', bg: 'surface' }],
  ['FloatTitle', { fg: 'ink', bg: 'surface' }],
  ['Directory', { fg: 'fn' }],
  ['Question', { fg: 'fn' }],
  ['MoreMsg', { fg: 'ok' }],
  ['ModeMsg', { fg: 'ink' }],
  ['ErrorMsg', { fg: 'error' }],
  ['Underlined', { fg: 'fn', underline: true }],
  ['DiagnosticError', { fg: 'error' }],
  ['DiagnosticWarn', { fg: 'warning' }],
  ['DiagnosticInfo', { fg: 'fn' }],
  ['DiagnosticHint', { fg: 'faint' }],
  ['DiagnosticOk', { fg: 'ok' }],
  ['DiagnosticUnderlineError', { sp: 'error', undercurl: true }],
  ['DiagnosticUnderlineWarn', { sp: 'warning', undercurl: true }],
  ['DiagnosticUnderlineInfo', { sp: 'fn', undercurl: true }],
  ['DiagnosticUnderlineHint', { sp: 'faint', undercurl: true }],
];

// Legacy syntax groups shared by Vim and Neovim. Comments get italic.
export const VIM_SYNTAX = [
  ['Comment', 'faint', 'italic'],
  ['Constant', 'num'],
  ['String', 'str'],
  ['Character', 'str'],
  ['Number', 'num'],
  ['Boolean', 'num'],
  ['Identifier', 'ink'],
  ['Function', 'fn'],
  ['Statement', 'kw'],
  ['Keyword', 'kw'],
  ['Operator', 'punct'],
  ['PreProc', 'builtin'],
  ['Type', 'type'],
  ['Special', 'builtin'],
  ['Delimiter', 'punct'],
  ['Todo', 'kw'],
  ['Error', 'error'],
  ['WarningMsg', 'warning'],
  ['Title', 'fn', 'bold'],
];

// Neovim Tree-sitter groups prevent prose, object keys, and markup tags from
// falling back to plain ink. Classic Vim does not accept capture names.
export const NVIM_SYNTAX = [
  ...VIM_SYNTAX,
  ['@markup.heading', 'fn', 'bold'],
  ['@markup.strong', 'kw', 'bold'],
  ['@markup.italic', 'kw', 'italic'],
  ['@markup.raw', 'builtin'],
  ['@markup.link.label', 'fn'],
  ['@markup.link.url', 'fn', 'underline'],
  ['@markup.quote', 'faint', 'italic'],
  ['@markup.list', 'punct'],
  ['@property', 'builtin'],
  ['@variable.member', 'builtin'],
  ['@tag', 'type'],
  ['@tag.attribute', 'builtin'],
  ['@string.escape', 'num'],
  ['@diff.plus', 'ok'],
  ['@diff.minus', 'error'],
  ['@diff.delta', 'warning'],
];
