// Classic Vim 8/9 emitter. Vim and Neovim share the legacy highlight groups,
// but Vim needs :highlight commands and xterm-256 fallbacks.

import { hexToXterm256Index } from '../colors.js';
import { n, resolveAnsi, file } from './shared.js';
import { VIM_SYNTAX, VIM_UI_HIGHLIGHTS } from './vim-groups.js';

function vimHighlight(group, attributes, colors) {
  const parts = ['highlight', group];
  for (const [attribute, tokenOrStyle] of Object.entries(attributes)) {
    if (attribute === 'fg') {
      const hex = n(colors[tokenOrStyle]);
      parts.push(`guifg=${hex}`, `ctermfg=${hexToXterm256Index(hex)}`);
    } else if (attribute === 'bg') {
      const hex = n(colors[tokenOrStyle]);
      parts.push(`guibg=${hex}`, `ctermbg=${hexToXterm256Index(hex)}`);
    } else if (attribute === 'sp') {
      parts.push(`guisp=${n(colors[tokenOrStyle])}`);
    } else if (tokenOrStyle) {
      parts.push(`gui=${attribute}`, `cterm=${attribute}`);
    }
  }
  return parts.join(' ');
}

export function emitVimTheme(theme, ansiMapping) {
  const c = theme.colors;
  const lines = [
    `" Candela ${theme.name} — generated by scripts/generate.js, do not edit.`,
    'highlight clear',
    "if exists('syntax_on') | syntax reset | endif",
    `set background=${theme.mode}`,
    `let g:colors_name = 'candela-${theme.id}'`,
    '',
  ];
  for (const [group, attributes] of VIM_UI_HIGHLIGHTS) {
    lines.push(vimHighlight(group, attributes, c));
  }
  for (const [group, token, style] of VIM_SYNTAX) {
    lines.push(vimHighlight(group, { fg: token, ...(style ? { [style]: true } : {}) }, c));
  }

  lines.push('');
  const ansi = resolveAnsi(ansiMapping, c);
  lines.push(`let g:terminal_ansi_colors = [${ansi.map((hex) => `'${hex}'`).join(', ')}]`);
  lines.push('');
  return lines.join('\n');
}

export const vimThemeFile = (theme, ansiMapping, prefix = '') =>
  file(`${prefix}candela-${theme.id}.vim`, emitVimTheme(theme, ansiMapping));

export const emitVimPackage = (theme, ansiMapping) => ({ files: [vimThemeFile(theme, ansiMapping)] });
